/* 
{
    server: "",                 // 서버 (default efabwas ||  금상몰 efmf)
    path: "",    
    path: ""                    // 폴더명 기입.
    pageID: "",                 // 화면ID
    depth: {                    // 페이지 depth 
            level2: "", 
            level3: "",
            level4: "",
            level5: "",
            level6: "",
        }, 
    pageType: "",               // 배너, 약관, 컨텐츠, 이미지, openflag
    done: "",                   // 완료일
    modify: "",                 // 수정일
    status: "",                 // 상태
    note: ""                    // 수정 내역 및 히스토리 내역 메모  \n 으로 줄바꿈 가능
}, 
*** row data 추가 형식 예제 ***
{server: "", path:"", pageID: "", depth: { level2: "", level3: "", level4: "", level5: "", level6: ""}, pageType: "", done: "", modify: "", status: "", note: ""},

*** CMS 경로 설정 ***
1. path에는 파일이 속해있는 CMS 폴더명을 기재
2. pageID가 유니크하거나 _iframe으로 끝나는 경우, .html을 붙이면 OAB CMS 경로 연결
3. pageID가 iframe0으로 끝나면 OAB CMS 경로로 연결
4. pageID가 차세대 AB 화면ID 형식인 "F0"을 포함하는 경우 AB CMS 경로로 연결
*/

const cmsData = {
    data: [
        // 결제
        {path: "pay", pageID: "ABEP4100R_iframe01", depth: { level2: "결제", level3: "제로페이결제", level4: "출금계좌선택", level5: "제로페이 이벤트 배너 영역", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "pay", pageID: "ABEP6000R_iframe01", depth: { level2: "결제", level3: "해외QR결제", level4: "카드관리", level5: "체크카드 배너 영역", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "pay", pageID: "ABEP4001R_iframe01", depth: { level2: "결제", level3: "제로페이결제", level4: "모바일직불결제 서비스 이용약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "pay", pageID: "ABEP4001R_iframe02", depth: { level2: "결제", level3: "", level4: "개인(신용)정보 제3자 제공 동의 ", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "pay", pageID: "ABEP4001R_iframe03", depth: { level2: "결제", level3: "제로페이모바일상품권", level4: "개인(신용)정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "pay", pageID: "UI-PD-D11003", depth: { level2: "결제", level3: "해외결제", level4: "해외결제 서비스 이용약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "pay", pageID: "", depth: { level2: "결제", level3: "", level4: "개인(신용)정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},

        // 계좌관리
        {path: "account", pageID: "", depth: { level2: "계좌관리", level3: "한도제한 해제", level4: "금융거래목적확인서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "account", pageID: "", depth: { level2: "계좌관리", level3: "", level4: "대포통장근절 고객확인서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "account", pageID: "IB-04030600F01-P", depth: { level2: "계좌관리", level3: "", level4: "공공마이데이터 사용동의서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},

        // 공과금
        {path: "tax", pageID: "TS-01000000F01", depth: { level2: "공과금", level3: "납부하기", level4: "타이틀영역", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TS-01000000F02", depth: { level2: "공과금", level3: "", level4: "서브메인", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TS-02000000F01", depth: { level2: "공과금", level3: "납부내역", level4: "타이틀영역", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TS-02000000F02", depth: { level2: "공과금", level3: "", level4: "서브메인", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TS-03000000F01", depth: { level2: "공과금", level3: "자동납부", level4: "타이틀영역", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TS-03000000F02", depth: { level2: "공과금", level3: "", level4: "서브메인", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TS-04000000F01", depth: { level2: "공과금", level3: "지방세입금 전자고지", level4: "타이틀영역", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TS-05000000F01", depth: { level2: "공과금", level3: "교육청 스마트고지", level4: "타이틀영역", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TS-06000000F01", depth: { level2: "공과금", level3: "스마트 스쿨뱅킹", level4: "타이틀영역", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "", depth: { level2: "공과금", level3: "아파트관리비 자동이체", level4: "아파트관리비 자동이체 신청 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "", depth: { level2: "공과금", level3: "지로자동납부", level4: "자동납부약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "", depth: { level2: "공과금", level3: "지방세 전자고지신청", level4: "지방세 전자고지 송달 서비스 약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "", depth: { level2: "공과금", level3: "", level4: "개인정보 제3자 제공동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TA-06010201F01-P", depth: { level2: "공과금", level3: "지로/생활요금", level4: "아파트관리비 자동이체", level5: "자동계아파트관리비 자동이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TA-09010201F01-P", depth: { level2: "공과금", level3: "", level4: "지로자동납부", level5: "자동계좌이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TC-02010200F01-P", depth: { level2: "공과금", level3: "전자고지", level4: "지방세입금전자고지신청/해지", level5: "전체약관동의(전자송달 미적용(미신청) Case)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TC-02010204F01-P", depth: { level2: "공과금", level3: "", level4: "", level5: "전체약관동의(전자송달 적용 Case)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TC-02010201F01-P", depth: { level2: "공과금", level3: "", level4: "", level5: "지방세∙지방세세외수입금 전자송달 이용약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TC-02010202F01-P", depth: { level2: "공과금", level3: "", level4: "", level5: "지방세∙지방세세외수입금 전자고지 이용약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "TC-02010203F01-P", depth: { level2: "공과금", level3: "", level4: "", level5: "개인정보 제3자 제공동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},

        // 공통
        {path: "util", pageID: "main_notice_openflag", depth: { level2: "공통", level3: "올원공지팝업", level4: "", level5: "", level6: ""}, pageType: "openflag", done: "", modify: "", status: "", note: "올원 공지 팝업 레이어팝업 노출여부 제어관리"},
        {path: "utility", pageID: "UA-03010000F01", depth: { level2: "공통", level3: "회원가입", level4: "계좌번호인증", level5: "패스제휴 이벤트 응모하기 배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "contents_2022", pageID: "UI-PD-E18102_iframe", depth: { level2: "공통", level3: "", level4: "개인(신용)정보 수집·이용·제공 동의서 (NH멤버스 회원가입용)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "contents_2022", pageID: "UI-PD-E18103_iframe", depth: { level2: "공통", level3: "", level4: "개인(신용)정보 수집·이용·제공 동의서(선택) (NH멤버스 상품서비스 안내 등)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "contents_2022", pageID: "UI-PD-E18108_iframe", depth: { level2: "공통", level3: "", level4: "NH멤버스 회원약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe01", depth: { level2: "공통", level3: "", level4: "전자금융거래 기본약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe02", depth: { level2: "공통", level3: "", level4: "NH올원뱅크 서비스 기본약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe03", depth: { level2: "공통", level3: "", level4: "개인(신용)정보 수집 이용 동의서(필수) (올원뱅크서비스)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe04", depth: { level2: "공통", level3: "", level4: "개인(신용)정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe05", depth: { level2: "공통", level3: "", level4: "NH올원뱅크 서비스 설명서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe06", depth: { level2: "공통", level3: "", level4: "위치기반 서비스 기본약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABCN1002R_iframe01", depth: { level2: "공통", level3: "", level4: "마케팅푸시 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABCN1002R_iframe02", depth: { level2: "공통", level3: "", level4: "개인(신용)정보 수집·이용·제공 동의서(상품서비스 안내 등)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02010000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "전자금융거래 기본약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02020000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "올원뱅크 서비스 기본약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02030000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "Step1 올원뱅크 서비스 설명서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02140000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "개인정보 수집이용 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02040000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "개인정보 제3자 제공 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02060000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "위치기반 서비스 기본약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02070000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "마케팅푸시 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02080000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "개인정보 수집·이용·제공 동의서(상품서비스 안내 등)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02110000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "약관 전체 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02120000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "필수 전체 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-02130000F01-P", depth: { level2: "공통", level3: "", level4: "Step1 약관동의", level5: "선택 전체 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-08000000F01", depth: { level2: "공통", level3: "", level4: "Step5 회원가입완료", level5: "입출금계좌개설 배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-08000000F02", depth: { level2: "공통", level3: "", level4: "Step5 회원가입완료", level5: "코드입력만 하면 끝 배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UA-08000000F03", depth: { level2: "공통", level3: "", level4: "Step5 회원가입완료", level5: "올원계좌 등록 배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UD-80010100F01-P", depth: { level2: "공통", level3: "오픈뱅킹", level4: "오픈뱅킹 서비스 이용약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UD-80010200F01-P", depth: { level2: "공통", level3: "", level4: "오픈뱅킹 출금/조회 약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UD-80010400F01-P", depth: { level2: "공통", level3: "", level4: "금융거래정보제공 동의서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UD-90020100F01-P", depth: { level2: "공통", level3: "기타", level4: "PASS앱인증", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-01000000F01-P", depth: { level2: "공통", level3: "", level4: "휴대폰 본인인증", level5: "전체약관동의(KT)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-02000000F01-P", depth: { level2: "공통", level3: "", level4: "", level5: "전체약관동의(LG U+)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-03000000F01-P", depth: { level2: "공통", level3: "", level4: "", level5: "전체약관동의(SKT)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-01010000F01-P", depth: { level2: "공통", level3: "", level4: "", level5: "개인정보수집·이용동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-01020000F01-P", depth: { level2: "공통", level3: "", level4: "", level5: "개인정보 제3자 제공동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-01030000F01-P", depth: { level2: "공통", level3: "", level4: "", level5: "서비스 이용약관 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-01040100F01-P", depth: { level2: "공통", level3: "", level4: "", level5: "통신사 이용약관 동의(KT)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-01040200F01-P", depth: { level2: "공통", level3: "", level4: "", level5: "통신사 이용약관 동의(LG U+)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UF-01040300F01-P", depth: { level2: "공통", level3: "", level4: "", level5: "통신사 이용약관 동의(SKT)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "utility", pageID: "UB-02020000F01", depth: { level2: "공통", level3: "회원확인", level4: "계좌인증", level5: "입출금계좌개설 배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ipetc1726l_iframe01", depth: { level2: "공통", level3: "휴대폰인증", level4: "개인정보 수집 및 이용 동의", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ipetc1726l_iframe02", depth: { level2: "공통", level3: "", level4: "개인정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ipetc1726l_iframe03", depth: { level2: "공통", level3: "", level4: "서비스 이용약관 동의", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {server: "efmf", path: "util", pageID: "ipetc1726l_iframe01", depth: { level2: "공통", level3: "휴대폰인증(금상몰 EFMF)", level4: "개인정보 수집 및 이용 동의", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: "금상몰 서버 efmf 업로드\n(금상몰 서버HMCMF-올원관리)도메인 + /content/cms/util/"},
        {server: "efmf", path: "util", pageID: "ipetc1726l_iframe02", depth: { level2: "공통", level3: "휴대폰인증(금상몰 EFMF)", level4: "개인정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: "금상몰 서버 efmf 업로드(금상몰 서버HMCMF-올원관리)도메인 + /content/cms/util/"},
        {server: "efmf", path: "util", pageID: "ipetc1726l_iframe03", depth: { level2: "공통", level3: "휴대폰인증(금상몰 EFMF)", level4: "서비스 이용약관 동의", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: "금상몰 서버 efmf 업로드(금상몰 서버HMCMF-올원관리)도메인 + /content/cms/util/"},
        {server: "efmf", path: "util", pageID: "ipel0723r_t08.html", depth: { level2: "공통", level3: "휴대폰인증(금상몰 EFMF)", level4: "통신사 이용약관 동의(LG)", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: "금상몰 서버 efmf 업로드\n(금상몰 서버HMCMF-올원관리)도메인 + /content/html/ip/el/clause/"},
        {server: "efmf", path: "util", pageID: "ipel0723r_t10.html", depth: { level2: "공통", level3: "휴대폰인증(금상몰 EFMF)", level4: "통신사 이용약관 동의(SKT)", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: "금상몰 서버 efmf 업로드\n(금상몰 서버HMCMF-올원관리)도메인 + /content/html/ip/el/clause/"},
        {server: "efmf", path: "util", pageID: "ipel0723r_t07.html", depth: { level2: "공통", level3: "휴대폰인증(금상몰 EFMF)", level4: "통신사 이용약관 동의(KT)", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: "금상몰 서버 efmf 업로드\n(금상몰 서버HMCMF-올원관리)도메인 + /content/html/ip/el/clause/"},
        
        // 금융
        {path: "finance", pageID: "FA-04000000F01", depth: { level2: "금융", level3: "송금하기", level4: "송금완료배너", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "ABOT1019I_iframe01", depth: { level2: "금융", level3: "올원송금", level4: "올원송금받기(web)", level5: "개인정보 수집 이용 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "ABOT5110R_iframe01", depth: { level2: "금융", level3: "자동이체", level4: "자동이체신청", level5: "농협자동이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "ABOT5120R_iframe01", depth: { level2: "금융", level3: "", level4: "", level5: "타행자동이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "ABOT5110R_iframe02", depth: { level2: "금융", level3: "", level4: "농협계좌로 자동이체", level5: "계좌간 자동이체 약관(NH농협은행)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "ABOT5110R_iframe03", depth: { level2: "금융", level3: "", level4: "", level5: "계좌간 자동이체 약관(농·축협 )", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "ABOT5120R_iframe02", depth: { level2: "금융", level3: "", level4: "타행계좌로 자동이체", level5: "타행 자동이체 약관(NH농협은행)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "ABOT5120R_iframe03", depth: { level2: "금융", level3: "", level4: "", level5: "타행 자동이체 약관(농·축협 )", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "tax", pageID: "ipam1604r_iframe.html", depth: { level2: "금융", level3: "계좌이동제", level4: "자동납부등록내역조회/변경", level5: "자동납부 출금계좌 변경신청 유의 사항", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "", depth: { level2: "금융", level3: "", level4: "", level5: "계좌이동 서비스 통합 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "통합스마트뱅킹 경로"},
        {path: "bank", pageID: "", depth: { level2: "금융", level3: "", level4: "", level5: "펌뱅킹 출금이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "통합스마트뱅킹 경로"},
        {path: "bank", pageID: "", depth: { level2: "금융", level3: "", level4: "", level5: "금융결제원 CMS 출금이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "통합스마트뱅킹 경로"},
        {path: "bank", pageID: "", depth: { level2: "금융", level3: "", level4: "", level5: "자동계좌이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "통합스마트뱅킹 경로"},
        {path: "tax", pageID: "ipam1604r_iframe.html", depth: { level2: "금융", level3: "", level4: "자동송금내역조회/변경", level5: "자동송금 출금계좌 변경신청 유의사항", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "bank", pageID: "", depth: { level2: "금융", level3: "", level4: "", level5: "계좌이동 서비스 통합 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "통합스마트뱅킹 경로"},
        {path: "bank", pageID: "", depth: { level2: "금융", level3: "", level4: "", level5: "계좌간자동이체 약관  ", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "통합스마트뱅킹 경로"},
        {path: "bank", pageID: "", depth: { level2: "금융", level3: "", level4: "", level5: "납부자자동이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "통합스마트뱅킹 경로"},
        {path: "bank", pageID: "", depth: { level2: "금융", level3: "", level4: "", level5: "타행자동이체 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "통합스마트뱅킹 경로"},
        {path: "finance", pageID: "FM-03010000F01-P", depth: { level2: "금융", level3: "전계좌조회", level4: "다른기관", level5: "어카운트인포 약관동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},


        // 금융그룹
        {path: "group", pageID: "GA-00000000F01", depth: { level2: "금융그룹", level3: "메인", level4: "이벤트 배너", level5: "", level6: ""}, pageType: "배너", done: "20230502", modify: "", status: "", note: ""},
        {path: "group", pageID: "GA-00000000F02", depth: { level2: "금융그룹", level3: "", level4: "테마별 추천 서비스", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "group", pageID: "GA-00000000F03", depth: { level2: "금융그룹", level3: "", level4: "아이콘 메뉴", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "group", pageID: "GA-00000000F04", depth: { level2: "금융그룹", level3: "", level4: "계열사 추천 상품", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230530", modify: "", status: "", note: ""},
        {path: "group", pageID: "UI-PD-N07081_iframe01", depth: { level2: "금융그룹", level3: "NH투자증권", level4: "제3자 정보 제공동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "UI-PD-N07081_iframe02", depth: { level2: "금융그룹", level3: "NH농협생명보험", level4: "제3자 정보 제공동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "UI-PD-N07081_iframe03", depth: { level2: "금융그룹", level3: "NH농협캐피탈", level4: "제3자 정보 제공동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "UI-PD-N07081_iframe04", depth: { level2: "금융그룹", level3: "NH저축은행", level4: "제3자 정보 제공동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "UI-PD-N07081_iframe05", depth: { level2: "금융그룹", level3: "NH농협손해보험", level4: "제3자 정보 제공동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe01", depth: { level2: "금융그룹", level3: "다모아대출", level4: "농협은행약관", level5: "개인(신용)정보 수집·이용 및 제공 관련 고객 권리 안내문", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe02", depth: { level2: "금융그룹", level3: "", level4: "농협은행약관", level5: "개인(신용)정보 수집·이용·제공 동의서(필수)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe03", depth: { level2: "금융그룹", level3: "", level4: "농협은행약관", level5: "개인(신용)정보 조회 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe04", depth: { level2: "금융그룹", level3: "", level4: "농협은행약관", level5: "건강보험공단 정보 이용동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe07", depth: { level2: "금융그룹", level3: "", level4: "농협생명약관", level5: "농협생명보험㈜ 관련 개인(신용)정보 제공 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe08", depth: { level2: "금융그룹", level3: "", level4: "손해보험약관", level5: "농협손해보험㈜ 관련 개인(신용)정보 제공 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe09", depth: { level2: "금융그룹", level3: "", level4: "캐피탈약관", level5: "개인(신용)정보 필수적 동의서 (수집·이용·조회·제공)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe10", depth: { level2: "금융그룹", level3: "", level4: "저축은행약관", level5: "NH저축은행㈜ 관련 개인(신용)정보 제공 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "ABTS5202I_iframe14", depth: { level2: "금융그룹", level3: "", level4: "캐피탈약관", level5: "NH농협캐피탈㈜ 관련 개인(신용)정보 제공 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "", depth: { level2: "금융그룹", level3: "NH멤버스", level4: "개인(신용)정보 수집·이용·제공 동의서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "", depth: { level2: "금융그룹", level3: "", level4: "NH멤버스 회원약관 ", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "group", pageID: "", depth: { level2: "금융그룹", level3: "", level4: "개인(신용)정보 수집·이용·제공 동의서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},

        // 마이올원
        {path: "util", pageID: "abetc1759c_iframe08", depth: { level2: "마이올원", level3: "타행계좌등록/관리", level4: "농협은행 고객등록", level5: "(비여신) 개인(신용)정보 수집·이용 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe07", depth: { level2: "마이올원", level3: "", level4: "", level5: "NH농협금융 고객정보 취급방침", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABMO1501R_iframe01", depth: { level2: "마이올원", level3: "", level4: "어카운트 인포약관", level5: "오픈뱅킹 서비스 이용약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABMO1501R_iframe02", depth: { level2: "마이올원", level3: "", level4: "", level5: "오픈뱅킹 출금/조회 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABMO1501R_iframe03", depth: { level2: "마이올원", level3: "", level4: "", level5: "개인(신용)정보 수집이용 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABMO1501R_iframe04", depth: { level2: "마이올원", level3: "", level4: "", level5: "금융거래정보제공 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABMO1501R_iframe05", depth: { level2: "마이올원", level3: "", level4: "", level5: "[선택] 개인신용정보 수집이용동의서(오픈뱅킹용)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABMO1501R_iframe06", depth: { level2: "마이올원", level3: "", level4: "어카운트 인포약관(1년초과시노출)", level5: "계좌통합관리서비스 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "UI-PD-C17159_iframe01", depth: { level2: "마이올원", level3: "", level4: "PASS앱 추심이체 출금동의", level5: "개인(신용)정보 수집이용 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ums_iframe01", depth: { level2: "마이올원", level3: "입출금알림", level4: "농협은행/농축협 UMS이용약관", level5: "농협 통합메시징서비스(UMS) 이용약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe08", depth: { level2: "마이올원", level3: "나의정보변경(농협은행)", level4: "고객정보(농협은행)변경", level5: "(비여신) 개인(신용)정보 수집·이용 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABCN1002R_iframe02", depth: { level2: "마이올원", level3: "마케팅 동의 설정", level4: "개인(신용)정보 수집·이용·제공 동의서(상품서비스 안내 등)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "etc", pageID: "abts7027r_iframe01", depth: { level2: "마이올원", level3: "NH포인트", level4: "쇼핑몰 배너", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABMA3103R_iframe01", depth: { level2: "마이올원", level3: "하나로가족", level4: "선정기준표", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "UI-PD-C05004_iframe01", depth: { level2: "마이올원", level3: "입출금알림", level4: "마케팅배너", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "UI-PD-C05004_iframe02", depth: { level2: "마이올원", level3: "", level4: "마케팅배너", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABNM1001I_iframe03", depth: { level2: "마이올원", level3: "NH프로포즈", level4: "상품몰", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABNM1001I_iframe04", depth: { level2: "마이올원", level3: "", level4: "프로포즈 혜택", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "myallone", pageID: "AC-01000000F01", depth: { level2: "마이올원", level3: "내가 받은 혜택", level4: "이벤트 배너", level5: "", level6: ""}, pageType: "배너", done: "20230421", modify: "", status: "", note: ""},
        {path: "myallone", pageID: "", depth: { level2: "마이올원", level3: "서비스관리", level4: "영업점 방문예약", level5: "사전상담표 작성", level6: ""}, pageType: "", done: "", modify: "", status: "", note: ""},
        {path: "myallone", pageID: "AJ-05020300F01-P", depth: { level2: "마이올원", level3: "", level4: "", level5: "", level6: "영업점 방문예약(기타)"}, pageType: "약관", done: "20230904", modify: "", status: "", note: ""},
        {path: "myallone", pageID: "AJ-05020300F02-P", depth: { level2: "마이올원", level3: "", level4: "", level5: "", level6: "영업점 방문예약(개인예금)"}, pageType: "약관", done: "20230904", modify: "", status: "", note: ""},
        {path: "myallone", pageID: "AJ-05020300F03-P", depth: { level2: "마이올원", level3: "", level4: "", level5: "", level6: "영업점 방문예약(개인사업자대출)"}, pageType: "약관", done: "20230904", modify: "", status: "", note: ""},
        {path: "myallone", pageID: "AJ-05020300F04-P", depth: { level2: "마이올원", level3: "", level4: "", level5: "", level6: "영업점 방문예약(개인대출)"}, pageType: "약관", done: "20230904", modify: "", status: "", note: ""},

        // 메인
        {path: "home", pageID: "HA-04000000F01-L", depth: { level2: "메인", level3: "메인", level4: "로그아웃안내 팝업", level5: "배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "home", pageID: "HA-04000000F01-L", depth: { level2: "메인", level3: "", level4: "종료 여부 확인 팝업", level5: "배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "contents_2022", pageID: "UI-PD-E03002", depth: { level2: "메인", level3: "AI톡", level4: "AI톡 대화", level5: "퀵메뉴", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "contents_2022", pageID: "UI-PD-E03003", depth: { level2: "메인", level3: "", level4: "", level5: "자주하는 질문", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABCB0001R_iframe01", depth: { level2: "메인", level3: "", level4: "", level5: "FAQ", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABVR2000P_iframe01", depth: { level2: "메인", level3: "NUGU음성서비스", level4: "개인(신용)정보 수집 이용 제공 동의서(올원뱅크 내 음성뱅킹 서비스)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "home", pageID: "HE-07000000F01-P", depth: { level2: "메인", level3: "", level4: "음성약관동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "home", pageID: "HE-07010000F01-P", depth: { level2: "메인", level3: "", level4: "음성약관동의(다크모드)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "login_notice_iframe", depth: { level2: "메인", level3: "시스템점검팝업", level4: "", level5: "", level6: ""}, pageType: "이미지", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "main_notice_openflag", depth: { level2: "메인", level3: "공지사항 open_flag", level4: "", level5: "", level6: ""}, pageType: "openflag", done: "", modify: "", status: "", note: ""},
        {path: "main_page", pageID: "popup_sysnotice.png", depth: { level2: "메인", level3: "시스템점검이미지", level4: "", level5: "", level6: ""}, pageType: "이미지", done: "", modify: "", status: "", note: ""},
        {path: "home", pageID: "img-event-deco.png", depth: { level2: "메인", level3: "메인데코", level4: "", level5: "", level6: ""}, pageType: "이미지", done: "", modify: "", status: "", note: ""},
        {path: "home", pageID: "HA-01000000F01", depth: { level2: "메인", level3: "이벤트배너", level4: "", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: "[231018] 고객지원반 관리 파일"},

        // 상품
        { server: "efmf", path: "util", pageID: "mnra0002t.html", depth: { level2: "상품", level3: "입출금계좌개설", level4: "약관동의", level5: "개인(신용)정보 수집·이용·제공 동의서(상품서비스 안내 등)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "금상몰서버 /content/nhbank/html/mn/"},
        { server: "efmf", path: "util", pageID: "mnra0001t.html", depth: { level2: "상품", level3: "", level4: "", level5: "개인(신용)정보 수집·이용 동의(비여신거래)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "금상몰서버 /content/nhbank/html/mn/"},
        { server: "efmf", path: "util", pageID: "mnra0003t.html", depth: { level2: "상품", level3: "", level4: "", level5: "개인(신용)정보 수집·이용·제공 동의 (상품서비스 안내 등)(농협금융지주 자회사간 상호 정보 제공용)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "금상몰서버 /content/nhallone/cms/util/"},
        {server:"nhallone", path: "product", pageID: "PROTECT_iframe.html", depth: { level2: "상품", level3: "", level4: "상품상세(상품공통)", level5: "예금자 보호(상품 공통)", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10001052_iframe01", depth: { level2: "상품", level3: "", level4: "NH페이모아통장 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10001052_iframe01", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10000839_iframe01", depth: { level2: "상품", level3: "", level4: "NH주거래우대통장 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10000839_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABMN1219R_3_iframe01", depth: { level2: "상품", level3: "", level4: "NH주거래우대통장 개설완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10001015_iframe01", depth: { level2: "상품", level3: "", level4: "NH1934우대통장 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10001015_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABMN1219R_1_iframe01", depth: { level2: "상품", level3: "", level4: "NH1934우대통장 개설완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10000927_iframe01", depth: { level2: "상품", level3: "", level4: "NH X 카카오페이통장 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10000927_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABMN1219R_4_iframe01", depth: { level2: "상품", level3: "", level4: "NH X 카카오페이통장 개설완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10000967_iframe01", depth: { level2: "상품", level3: "", level4: "NH모여라통장(저축예금) 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {server:"nhallone", path: "product", pageID: "ABME1203R_10000967_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABMN1219R_2_iframe01", depth: { level2: "상품", level3: "", level4: "NH모여라통장(저축예금) 개설완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {server:"efmf", path: "market", pageID: "UI-PD-N08210_iframe01", depth: { level2: "상품", level3: "", level4: "개설완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: "(금상몰 서버HMCMF-올원관리)/content/contents/cm/"},
        {path: "market", pageID: "ABML1059R_iframe01", depth: { level2: "상품", level3: "", level4: "올원 신용대출 실행완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABML1065R_iframe01", depth: { level2: "상품", level3: "", level4: "올원 비상금대출 실행완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABML4114R_iframe01", depth: { level2: "상품", level3: "", level4: "모바일아파트대출2.0 신청완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABML1023R_iframe01", depth: { level2: "상품", level3: "", level4: "단기카드대출 실행완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABTS7000R_iframe03", depth: { level2: "상품", level3: "", level4: "올원신용대출 심사부결", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "util", server:'efmf', pageID: "", depth: { level2: "상품", level3: "", level4: "휴대폰인증", level5: "개인정보 수집 및 이용 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "경로확인불가"},
        {path: "util", server:'efmf', pageID: "", depth: { level2: "상품", level3: "", level4: "", level5: "개인정보 제3자 제공 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "경로확인불가"},
        {path: "util", server:'efmf', pageID: "", depth: { level2: "상품", level3: "", level4: "", level5: "서비스 이용약관 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "경로확인불가"},
        {path: "util", server:'efmf', pageID: "", depth: { level2: "상품", level3: "", level4: "", level5: "통신사 이용약관 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "경로확인불가"},
        {path: "util", pageID: "ABCN1002R_iframe02", depth: { level2: "상품", level3: "예/적금, 대출상품 공통", level4: "개인(신용)정보 수집·이용·제공 동의서(상품서비스 안내 등)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "경로확인불가"},
        {path: "util", pageID: "abetc1759c_iframe08", depth: { level2: "상품", level3: "", level4: "(비여신) 개인(신용)정보 수집·이용 동의서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "abetc1759c_iframe07", depth: { level2: "상품", level3: "", level4: "NH농협금융 고객정보 취급방침", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "util", pageID: "ABCN1002R_iframe04", depth: { level2: "상품", level3: "", level4: "개인(신용)정보 수집·이용·제공 동의 (상품서비스 안내 등)(농협금융지주 자회사간 상호 정보 제공용)", level5: "", level6: ""}, pageType: "약관", done: "20231017", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1340R_iframe01", depth: { level2: "상품", level3: "예/적금", level4: "올원캔디예금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1340R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME1344R_iframe01", depth: { level2: "상품", level3: "", level4: "올원캔디예금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1233R_iframe01", depth: { level2: "상품", level3: "", level4: "e금리우대예금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1233R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME1237R_iframe01", depth: { level2: "상품", level3: "", level4: "e금리우대예금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "abme1390r_iframe01", depth: { level2: "상품", level3: "", level4: "NH걷고싶은 대한민국 적금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "abme1390r_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME1392R_iframe01", depth: { level2: "상품", level3: "", level4: "NH걷고싶은 대한민국 적금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME2205R_iframe01", depth: { level2: "상품", level3: "", level4: "NH샀다치고적금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME2205R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME2005R_iframe01", depth: { level2: "상품", level3: "", level4: "NH샀다치고적금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1280R_iframe01", depth: { level2: "상품", level3: "", level4: "올원 5늘도 적금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1280R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME1285R_iframe01", depth: { level2: "상품", level3: "", level4: "NH올원 5늘도 적금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1238R_iframe01", depth: { level2: "상품", level3: "", level4: "e금리우대적금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1238R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME1242R_iframe01", depth: { level2: "상품", level3: "", level4: "e금리우대적금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME3252R_iframe01", depth: { level2: "상품", level3: "", level4: "NH직장인월복리적금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME3252R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME3256R_iframe01", depth: { level2: "상품", level3: "", level4: "NH직장인월복리적금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1440R_iframe01", depth: { level2: "상품", level3: "", level4: "NH올원e예금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1440R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1243R_iframe01", depth: { level2: "상품", level3: "", level4: "주택청약종합저축 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABME1243R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "PROTECT_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "예금자보호(주택청약)", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME1248R_iframe01", depth: { level2: "상품", level3: "", level4: "주택청약종합저축 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "abmep1280r_iframe01", depth: { level2: "상품", level3: "", level4: "NH올원e 미니적금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "abmep1280r_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "기타", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "abmep1285r_iframe01", depth: { level2: "상품", level3: "", level4: "NH올원e 미니적금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABEF3010R_iframe01", depth: { level2: "상품", level3: "", level4: "올원외화포켓적립예금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABEF3010R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "제한사항", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABEF3010R_iframe03", depth: { level2: "상품", level3: "", level4: "", level5: "금리안내", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABEF3030R_iframe01", depth: { level2: "상품", level3: "", level4: "올원외화포켓적립예금 가입완료", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "product", pageID: "abme1500r_iframe01", depth: { level2: "상품", level3: "", level4: "NH고향사랑기부예금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "20231011", status: "", note: "[AL2304_P002] NH고향사랑기부예적금 문구 수정"},
        {path: "market", pageID: "10001196_prpe.html", depth: { level2: "상품", level3: "", level4: "", level5: "고향사랑기부예금 우대금리동의서", level6: ""}, pageType: "약관", done: "20230502", modify: "", status: "", note: ""},
        {path: "product", pageID: "abme1500r_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "유의사항", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "20231011", status: "", note: "[AL2304_P002] NH고향사랑기부예적금 문구 수정"},
        {path: "market", pageID: "ABMEP1504R_iframe01", depth: { level2: "상품", level3: "", level4: "", level5: "가입완료", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "product", pageID: "abme1510r_iframe01", depth: { level2: "상품", level3: "", level4: "NH고향사랑기부적금 상품상세", level5: "우대금리", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "20231011", status: "", note: "[AL2304_P002] NH고향사랑기부예적금 문구 수정"},
        {path: "market", pageID: "10001197_prpe.html", depth: { level2: "상품", level3: "", level4: "", level5: "고향사랑기부적금 우대금리동의서", level6: ""}, pageType: "약관", done: "20230502", modify: "", status: "", note: ""},
        {path: "product", pageID: "abme1510r_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "유의사항", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "20231011", status: "", note: "[AL2304_P002] NH고향사랑기부예적금 문구 수정"},
        {path: "market", pageID: "ABMEP1513R_iframe01", depth: { level2: "상품", level3: "", level4: "", level5: "가입완료", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8037R_iframe01", depth: { level2: "상품", level3: "골드바", level4: "골드바 상품개요", level5: "구매 및 수령정보", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8048R_iframe01", depth: { level2: "상품", level3: "", level4: "", level5: "구매완료", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8052R_iframe01", depth: { level2: "상품", level3: "", level4: "", level5: "금투자포인트", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8044R_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "골드바 이용 안내", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8044R_iframe01", depth: { level2: "상품", level3: "", level4: "", level5: "금 가격의 변동 가능성", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8044R_iframe06", depth: { level2: "상품", level3: "", level4: "", level5: "골드바 가격 변동 가능성", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8044R_iframe07", depth: { level2: "상품", level3: "", level4: "", level5: "골드바 가격 계산 및 수수료율", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8044R_iframe08", depth: { level2: "상품", level3: "", level4: "", level5: "상품설명서 및 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8201R_iframe01", depth: { level2: "상품", level3: "실버바", level4: "실버바 상품개요", level5: "구매 및 수령정보", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8217R_iframe01", depth: { level2: "상품", level3: "", level4: "", level5: "구매완료", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "silverbar_iframe06", depth: { level2: "상품", level3: "", level4: "", level5: "은투자포인트", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "silverbar_iframe01", depth: { level2: "상품", level3: "", level4: "", level5: "실버바 이용 안내", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "silverbar_iframe02", depth: { level2: "상품", level3: "", level4: "", level5: "은 가격의 변동 가능성", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "silverbar_iframe03", depth: { level2: "상품", level3: "", level4: "", level5: "실버바 가격 변동 가능성", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "silverbar_iframe04", depth: { level2: "상품", level3: "", level4: "", level5: "실버바 가격 계산 및 수수료율", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "silverbar_iframe05", depth: { level2: "상품", level3: "", level4: "", level5: "상품설명서 및 약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8053R.iframe02", depth: { level2: "상품", level3: "골드/실버바 FAQ", level4: "전체보기", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "ABME8053R.iframe01", depth: { level2: "상품", level3: "", level4: "골드바FAQ", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "market", pageID: "silverbar_iframe07", depth: { level2: "상품", level3: "", level4: "실버바FAQ", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "commodity", pageID: "CQ-02030100F01-P", depth: { level2: "상품", level3: "비대면기한연기", level4: "전체약관동의", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "commodity", pageID: "CQ-02030200F01-P", depth: { level2: "상품", level3: "", level4: "은행여신거래기본약관 (가계용)", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "commodity", pageID: "CQ-02030300F01-P", depth: { level2: "상품", level3: "", level4: "개인(신용)정보조회동의서", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "commodity", pageID: "CQ-02030400F01-P", depth: { level2: "상품", level3: "", level4: "행정기관개인(신용)정보조회 위임동의서", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "commodity", pageID: "CQ-02030500F01-P", depth: { level2: "상품", level3: "", level4: "행정기관개인(신용)정보수집·이용동의서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "commodity", pageID: "CQ-02030600F01-P", depth: { level2: "상품", level3: "", level4: "개인(신용)정보수집·이용및제공관련고객권리안내문", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "commodity", pageID: "CQ-02030700F01-P", depth: { level2: "상품", level3: "", level4: "[선택] 개인(신용)정보 수집·이용 및 제공 동의 (상품 서비스 안내 등)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},

        // 생활+
        {path: "life", pageID: "LA-00000000F01", depth: { level2: "생활+", level3: "메인", level4: "상단배너", level5: "", level6: ""}, pageType: "배너", done: "20230502", modify: "20230502", status: "", note: ""},
        {path: "life", pageID: "LA-00000000F06", depth: { level2: "생활+", level3: "", level4: "메뉴", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "life", pageID: "LA-00000000F07", depth: { level2: "생활+", level3: "", level4: "놀이터", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "life", pageID: "LA-00000000F08", depth: { level2: "생활+", level3: "", level4: "할인쿠폰", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "life", pageID: "LA-00000000F02", depth: { level2: "생활+", level3: "", level4: "플라워", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "life", pageID: "LA-00000000F03", depth: { level2: "생활+", level3: "", level4: "농협축산몰LYVLY", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "life", pageID: "LA-00000000F04", depth: { level2: "생활+", level3: "", level4: "농협몰", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "", status: "", note: ""},
        {path: "life", pageID: "LA-00000000F05", depth: { level2: "생활+", level3: "", level4: "기프티쇼", level5: "", level6: ""}, pageType: "컨텐츠", done: "20230502", modify: "20230502", status: "삭제", note: "[230502] 기프티쇼 삭제"},
        {path: "funlife", pageID: "UI-PD-KF-D10000_2_iframe.html", depth: { level2: "생활+", level3: "올원X플라워", level4: "서비스 이용 약관 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "UI-PD-KF-D10000_1_iframe.html", depth: { level2: "생활+", level3: "", level4: "개인정보처리방침", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "UI-PD-KF-D10000_3_iframe.html", depth: { level2: "생활+", level3: "", level4: "개인정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "UI-PD-D12001_3.html", depth: { level2: "생활+", level3: "올원X방문택배", level4: "택배 이용 약관 동의(필수)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "UI-PD-D12001_4.html", depth: { level2: "생활+", level3: "", level4: "개인정보 처리방침(필수)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "UI-PD-D12001_5.html", depth: { level2: "생활+", level3: "", level4: "개인정보 제3자 제공 동의(필수)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "UI-PD-D12001_2.html", depth: { level2: "생활+", level3: "올원공구", level4: "개인정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "ABFL0948I_iframe03", depth: { level2: "생활+", level3: "올원X농협몰", level4: "개인정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "LYVLY_iframe01", depth: { level2: "생활+", level3: "올원XLYVLY", level4: "서비스 이용약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "LYVLY_iframe02", depth: { level2: "생활+", level3: "올원XLYVLY", level4: "개인정보 처리방침", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "LYVLY_iframe03", depth: { level2: "생활+", level3: "올원XLYVLY", level4: "개인정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "NABFL1112P_iframe.html", depth: { level2: "생활+", level3: "프리미엄", level4: "개인정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "NABFL1111P_iframe.html", depth: { level2: "생활+", level3: "핫딜", level4: "개인(신용)정보 수집 이용 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "ABCU1808R_iframe02", depth: { level2: "생활+", level3: "생활플러스", level4: "개인정보 수집 이용 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "UI-PD-D18612.html", depth: { level2: "생활+", level3: "올원용돈관리", level4: "서비스 이용 약관 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "ABFL9045R_iframe01", depth: { level2: "생활+", level3: "기프티쇼", level4: "서비스 이용약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "ABFL9045R_iframe02", depth: { level2: "생활+", level3: "", level4: "개인정보 처리방침", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "ABFL9045R_iframe03", depth: { level2: "생활+", level3: "", level4: "개인정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "nfc_iframe06", depth: { level2: "생활+", level3: "교통카드(AOS)", level4: "서비스 안내", level5: "서비스 이용약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "nfc_iframe08", depth: { level2: "생활+", level3: "", level4: "", level5: "개인정보 취급방침", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "nfc_iframe07", depth: { level2: "생활+", level3: "", level4: "", level5: "개인(신용)정보 수집·이용·제공 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "nfc_iframe04", depth: { level2: "생활+", level3: "교통카드(AOS/iOS공용)", level4: "", level5: "전자금융이용약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "nfc_iframe01", depth: { level2: "생활+", level3: "교통카드(iOS)", level4: "", level5: "서비스 이용약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "nfc_iframe02", depth: { level2: "생활+", level3: "", level4: "", level5: "개인정보 취급방침", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "nfc_iframe05", depth: { level2: "생활+", level3: "", level4: "", level5: "개인(신용)정보 수집·이용·제공 동의서", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "life", pageID: "LH-03010101F01-P", depth: { level2: "생활+", level3: "기프티콘 플리마켓", level4: "서비스 약관동의", level5: "기프티콘 플리마켓 이용약관 동의", level6: ""}, pageType: "약관", done: "20230816", modify: "", status: "", note: ""},
        {path: "life", pageID: "LH-03010102F01-P", depth: { level2: "생활+", level3: "", level4: "", level5: "개인정보 처리방침", level6: ""}, pageType: "약관", done: "20230816", modify: "", status: "", note: ""},
        {path: "life", pageID: "LH-03010103F01-P", depth: { level2: "생활+", level3: "", level4: "", level5: "개인정보 제3자 제공 동의", level6: ""}, pageType: "약관", done: "20230816", modify: "", status: "", note: ""},
        {path: "life", pageID: "LH-02020000F01", depth: { level2: "생활+", level3: "올원X알뜰폰", level4: "서비스 약관동의", level5: "개인정보 제3자 제공 동의", level6: ""}, pageType: "약관", done: "20231017", modify: "", status: "", note: ""},
        {path: "life", pageID: "LI-02000000F01", depth: { level2: "생활+", level3: "부동산", level4: "뉴스레터", level5: "", level6: ""}, pageType: "배너", done: "20230818", modify: "", status: "", note: ""},
        {path: "life", pageID: "LI-04010100F01", depth: { level2: "생활+", level3: "", level4: "부동산 조각투자", level5: "부동산 조각투자 이용약관 동의", level6: ""}, pageType: "약관", done: "20230920", modify: "", status: "", note: ""},
        {path: "life", pageID: "LI-04010200F01", depth: { level2: "생활+", level3: "", level4: "", level5: "투자 유의사항", level6: ""}, pageType: "약관", done: "20230920", modify: "", status: "", note: ""},
        {path: "life", pageID: "LI-04010300F01", depth: { level2: "생활+", level3: "", level4: "", level5: "개인정보 처리방침", level6: ""}, pageType: "약관", done: "20230920", modify: "", status: "", note: ""},
        {path: "life", pageID: "LI-04010400F01", depth: { level2: "생활+", level3: "", level4: "", level5: "개인정보 3자 제공 동의", level6: ""}, pageType: "약관", done: "20230921", modify: "", status: "", note: ""},
        {path: "life", pageID: "LK-01010000F01-P", depth: { level2: "생활+", level3: "전기차", level4: "서비스이용안내", level5: "전기차 서비스 이용약관 동의", level6: ""}, pageType: "약관", done: "20230920", modify: "", status: "", note: ""},
        {path: "life", pageID: "LK-01020000F01-P", depth: { level2: "생활+", level3: "", level4: "", level5: "위치기반서비스 이용약관 동의", level6: ""}, pageType: "약관", done: "20230921", modify: "", status: "", note: ""},
        {path: "product", pageID: "ABGT2045R_iframe01", depth: { level2: "생활+", level3: "더+모임", level4: "NH모여라통장(큰만족실세예금)상세", level5: "기타 아코디언 영역", level6: ""}, pageType: "컨텐츠", done: "20230818", modify: "", status: "", note: ""},
        {path: "product", pageID: "PROTECT_iframe.html", depth: { level2: "생활+", level3: "", level4: "", level5: "예금자보호 영역", level6: ""}, pageType: "컨텐츠", done: "20230818", modify: "", status: "", note: ""},
        {path: "funlife", pageID: "UI-PD-D20402.html", depth: { level2: "생활+", level3: "올원명함", level4: "명함등록", level5: "배너", level6: ""}, pageType: "배너", done: "20230818", modify: "", status: "", note: ""},
        {path: "life", pageID: "LH-02010000F01", depth: { level2: "생활+", level3: "올원x알뜰폰", level4: "서비스소개", level5: "요금제안내", level6: ""}, pageType: "컨텐츠", done: "20231017", modify: "", status: "", note: ""},
        {path: "life", pageID: "LH-02010000F02", depth: { level2: "생활+", level3: "", level4: "", level5: "가입혜택안내", level6: ""}, pageType: "컨텐츠", done: "20231017", modify: "", status: "", note: ""},
        {path: "life", pageID: "LH-02010000F03", depth: { level2: "생활+", level3: "", level4: "", level5: "가입 유의사항", level6: ""}, pageType: "컨텐츠", done: "20231017", modify: "", status: "", note: ""},

        // 외환
        {path: "exchange", pageID: "EE-06000000F01-P", depth: { level2: "외환", level3: "공통", level4: "환율예약환전 서비스 약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06010000F01-P", depth: { level2: "외환", level3: "", level4: "외환거래 기본약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06020000F01-P", depth: { level2: "외환", level3: "", level4: "비여신 개인정보 수집·이용 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06030000F01-P", depth: { level2: "외환", level3: "", level4: "비대면 NH웨스턴유니온자동송금 거래약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06040000F01-P", depth: { level2: "외환", level3: "", level4: "개인정보 제3자 제공동의서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06050000F01-P", depth: { level2: "외환", level3: "", level4: "비대면 NH웨스턴유니온 사기주의 안내", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06060000F01-P", depth: { level2: "외환", level3: "", level4: "이용안내 및 유의사항", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-01020300F01", depth: { level2: "외환", level3: "환전", level4: "알뜰!환전 신청", level5: "내 외화박스에 옮겨담기 배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-01020300F02", depth: { level2: "외환", level3: "", level4: "알뜰!환전 신청", level5: "해외QR결제 서비스 배너", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-01010000F00", depth: { level2: "외환", level3: "", level4: "알뜰!환전 안내", level5: "타이틀 및 비쥬얼 영역", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-01010000F01", depth: { level2: "외환", level3: "", level4: "", level5: "환전신청 및 결제", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-01010000F02", depth: { level2: "외환", level3: "", level4: "", level5: "외화수령", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-01010000F03", depth: { level2: "외환", level3: "", level4: "", level5: "환율우대가이드", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-01010000F04", depth: { level2: "외환", level3: "", level4: "", level5: "기타 유의사항", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-02020000F00", depth: { level2: "외환", level3: "", level4: "너도나도! 환전", level5: "타이틀 및 비쥬얼 영역", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-02020000F01", depth: { level2: "외환", level3: "", level4: "", level5: "환전신청 및 결제", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-02020000F02", depth: { level2: "외환", level3: "", level4: "", level5: "외화수령", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-02020000F03", depth: { level2: "외환", level3: "", level4: "", level5: "환율우대가이드", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-02020000F04", depth: { level2: "외환", level3: "", level4: "", level5: "기타 유의사항", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-02030301F01-P", depth: { level2: "외환", level3: "", level4: "", level5: "전체약관동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-02030301F01-P", depth: { level2: "외환", level3: "", level4: "", level5: "외환거래 기본약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06020000F01-P", depth: { level2: "외환", level3: "", level4: "", level5: "환전신청", level6: "비여신 개인정보 수집 이용 동의"}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06020000F01-P", depth: { level2: "외환", level3: "", level4: "", level5: "환전내역조회", level6: "비여신 개인정보 수집 이용 동의"}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-03010000F00", depth: { level2: "외환", level3: "", level4: "환율예약환전", level5: "타이틀 및 비쥬얼 영역", level6: ""}, pageType: "", done: "컨텐츠", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-03020101F01-P", depth: { level2: "외환", level3: "", level4: "", level5: "전체약관동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-03020101F01-P", depth: { level2: "외환", level3: "", level4: "", level5: "외환거래 기본약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-03020101F01-P", depth: { level2: "외환", level3: "", level4: "", level5: "서비스약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-04010000F00", depth: { level2: "외환", level3: "", level4: "내맘대로외화BOX 안내", level5: "타이틀 및 비쥬얼 영역", level6: "컨텐츠"}, pageType: "", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-04010000F01", depth: { level2: "외환", level3: "", level4: "", level5: "외화BOX 이용안내", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-04010000F02", depth: { level2: "외환", level3: "", level4: "", level5: "외화BOX 이용가이드", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-04020300F01", depth: { level2: "외환", level3: "", level4: "", level5: "step3-외화BOX 담기 완료", level6: "NH스마트알림 서비스 배너"}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-05010000F00", depth: { level2: "외환", level3: "", level4: "외화선물보내기 안내", level5: "타이틀 및 비쥬얼 영역", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-05010000F02", depth: { level2: "외환", level3: "", level4: "", level5: "서비스 안내", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-01010000F00", depth: { level2: "외환", level3: "", level4: "안심! 해외송금", level5: "타이틀 및 비쥬얼 영역", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-01010000F01", depth: { level2: "외환", level3: "", level4: "", level5: "대상고객", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-01010000F02", depth: { level2: "외환", level3: "", level4: "", level5: "송금한도", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-01010000F03", depth: { level2: "외환", level3: "", level4: "", level5: "환율적용", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-01010000F04", depth: { level2: "외환", level3: "", level4: "", level5: "수수료", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-01010000F05", depth: { level2: "외환", level3: "", level4: "", level5: "신청시간", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-01010000F06", depth: { level2: "외환", level3: "", level4: "", level5: "기타사항", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EE-06010000F01-P", depth: { level2: "외환", level3: "", level4: "", level5: "외환거래 기본약관", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF0726R_iframe01", depth: { level2: "외환", level3: "", level4: "환율조회/계산기", level5: "환율조회(상세)", level6: "꼭 알아두세요"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF0728R_iframe01", depth: { level2: "외환", level3: "", level4: "", level5: "환전계산기/송금,외화예금 계산기/여행자수표계산기", level6: "꼭 알아두세요"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-07010000F00", depth: { level2: "외환", level3: "", level4: "거래외국환은행지정 안내", level5: "타이틀 및 비쥬얼 영역", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {server: "통합스마트뱅킹 경로", path: "exchange", pageID: "", depth: { level2: "외환", level3: "WU-AUTOSEND", level4: "외환거래 기본약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-02030101F01-P", depth: { level2: "외환", level3: "", level4: "WU-AUTOSEND 정보등록/조회 안내", level5: "전체약관동의", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-02010000F00", depth: { level2: "외환", level3: "", level4: "WU-AUTOSEND 정보등록/조회 안내", level5: "타이틀 및 비쥬얼 영역", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EB-02010000F01", depth: { level2: "외환", level3: "", level4: "", level5: "WU-AUTOSEND란?", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF5020R_iframe03", depth: { level2: "외환", level3: "", level4: "", level5: "NH특급송금서비스약관(kor)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF5020R_iframe03_eng", depth: { level2: "외환", level3: "", level4: "", level5: "NH특급송금서비스약관(eng)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF5020R_iframe03_viet", depth: { level2: "외환", level3: "", level4: "", level5: "NH특급송금서비스약관(viet)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF5020R_iframe04", depth: { level2: "외환", level3: "", level4: "", level5: "비대면NH웨스턴유니온자동송금거래약관(kor)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF5020R_iframe04_eng", depth: { level2: "외환", level3: "", level4: "", level5: "비대면NH웨스턴유니온자동송금거래약관(eng)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF5020R_iframe04_viet", depth: { level2: "외환", level3: "", level4: "", level5: "비대면NH웨스턴유니온자동송금거래약관(viet)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF4018I_iframe02", depth: { level2: "외환", level3: "감동! 외화선물", level4: "외화선물 보내기", level5: "서비스 안내", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF4018I_iframe01", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "꼭 알아두세요"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF5041P_iframe01", depth: { level2: "외환", level3: "", level4: "", level5: "외화선물 유의사항 팝업 상세내용", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-05010000F01", depth: { level2: "외환", level3: "", level4: "", level5: "외화선물조르기 배너", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "exchange", pageID: "EA-01020300F02", depth: { level2: "외환", level3: "", level4: "", level5: "Step3-외화선물 신청완료", level6: "해외QR결제 서비스 배너"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF5044P_iframe01", depth: { level2: "외환", level3: "", level4: "", level5: "재환전(되팔기) 팝업 상세내용", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF5045P_iframe01", depth: { level2: "외환", level3: "", level4: "", level5: "재환전(되팔기) 유의사항", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0301R_iframe01", depth: { level2: "외환", level3: "NH무계좌 해외송금", level4: "NH-ARGI무계좌 해외송금", level5: "서비스 안내(한국어)", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0301R_iframe03", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "환율 및 수수료 안내"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABVN0301R_iframe02", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "[중요] 이용안내 및 유의사항"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ef_provision.html", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "외환거래 기본약관"}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0301R_iframe01_eng", depth: { level2: "외환", level3: "", level4: "", level5: " 서비스 안내(영어)", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0301R_iframe03_eng", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "환율 및 수수료 안내"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABVN0301R_iframe02_eng", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "[중요] 이용안내 및 유의사항"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ef_004_t_eng.html", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "외환거래 기본약관"}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABVN0301R_iframe01_viet", depth: { level2: "외환", level3: "", level4: "", level5: "서비스 안내(베트남어)", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0301R_iframe03_viet", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "환율 및 수수료 안내"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABVN0301R_iframe02_viet", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "[중요] 이용안내 및 유의사항"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ef_004_t_viet.html", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "외환거래 기본약관"}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABVN0305R_iframe01", depth: { level2: "외환", level3: "", level4: "", level5: "신청 결과", level6: "마케팅 배너"}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0201I_iframe01_phil", depth: { level2: "외환", level3: "", level4: "NH-METRO무계좌 해외송금", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0201I_iframe02_phil", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "환율 및 수수료 안내"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABVN0301R_iframe02", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "[중요] 이용안내 및 유의사항"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ef_provision.html", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "외환거래 기본약관"}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0201I_iframe01_phil_eng", depth: { level2: "외환", level3: "", level4: "", level5: "서비스 안내(영어)", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABVN0201I_iframe02_phil_eng", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "환율 및 수수료 안내"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABVN0301R_iframe02_eng", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "[중요] 이용안내 및 유의사항"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ef_004_t_eng.html", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "외환거래 기본약관"}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABVN0301R_iframe02_viet", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "[중요] 이용안내 및 유의사항(viet)"}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ef_004_t_viet.html", depth: { level2: "외환", level3: "", level4: "", level5: "", level6: "외환거래 기본약관"}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF4140I_iframe02", depth: { level2: "외환", level3: "웨스턴유니온송금받기", level4: "웨스턴유니온송금받기 이용안내", level5: "이용안내", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF4140I_iframe03", depth: { level2: "외환", level3: "", level4: "", level5: "수수료 안내", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx2021", pageID: "ABEF4140I_iframe04", depth: { level2: "외환", level3: "", level4: "", level5: "유의사항", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF4140R_iframe01", depth: { level2: "외환", level3: "", level4: "", level5: "서비스이용약관 동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF4140R_iframe02", depth: { level2: "외환", level3: "", level4: "", level5: "개인정보 제3자 제공동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF4140R_iframe03", depth: { level2: "외환", level3: "", level4: "", level5: "개인정보 수집 이용 동의(상품별 필수)", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "fx", pageID: "ABEF4140R_iframe04", depth: { level2: "외환", level3: "", level4: "", level5: "자본거래 해당 시 영업점 방문수령", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},



        // 전체메뉴 
        {server: "efmfwas2015", path: "nhmyid", pageID: "ipetc1726l_iframe04", depth: { level2: "전체메뉴", level3: "MyID_실명인증 발급", level4: "[필수] 개인정보 수집 이용 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {server: "efmfwas2015", path: "nhmyid", pageID: "ipetc1726l_iframe05", depth: { level2: "전체메뉴", level3: "", level4: "[필수] 고유 식별정보 처리 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {server: "efmfwas2015", path: "nhmyid", pageID: "ipetc1726l_iframe07", depth: { level2: "전체메뉴", level3: "", level4: "[필수] 서비스 이용약관 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "navigation", pageID: "NA-00000000F01", depth: { level2: "전체메뉴", level3: "서브메인", level4: "올원뱅크 체험미션", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "navigation", pageID: "NF-01020000F01-P", depth: { level2: "전체메뉴", level3: "메뉴검색", level4: "올원하자 배너", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "navigation", pageID: "NF-01030000F01-P", depth: { level2: "전체메뉴", level3: "", level4: "올원신용대출 배너", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "ABCU1800R_iframe01", depth: { level2: "전체메뉴", level3: "고객센터", level4: "홈", level5: "사회공헌 활동소식 바로가기", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "ipcu_candyevent_newallone_202308.html", depth: { level2: "전체메뉴", level3: "", level4: "이벤트", level5: "캔디차감 이벤트", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "navigation", pageID: "NC-01000000F01", depth: { level2: "전체메뉴", level3: "", level4: "", level5: "룰렛이벤트", level6: ""}, pageType: "컨텐츠", done: "20231017", modify: "", status: "", note: ""},
        {path: "navigation", pageID: "NE-07040700F01-P", depth: { level2: "전체메뉴", level3: "", level4: "", level5: "개인(신용)정보수집이용제공 동의", level6: ""}, pageType: "약관", done: "20231017", modify: "", status: "", note: ""},
        {path: "navigation", pageID: "NE-07040701F01-P", depth: { level2: "전체메뉴", level3: "", level4: "", level5: "MISSION:POSSIBLE (신용)정보 수집이용제공 동의", level6: ""}, pageType: "약관", done: "20231017", modify: "", status: "", note: ""},
        {path: "cs", pageID: "ipcu1841l_iframe_faq.html", depth: { level2: "전체메뉴", level3: "FAQ", level4: "FAQ콘텐츠", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "navigation", pageID: "NE-12030301F01-T", depth: { level2: "전체메뉴", level3: "서비스 이용시간 안내", level4: "송금/조회", level5: "", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: "송금/조회, 신고/변경, 계좌관리, 금융, 상품, 결제, 외환, 공과금, 생활+, 마이데이터 서비스 안내 Tab"},
        {path: "cs", pageID: "abcu1908i_iframe01", depth: { level2: "전체메뉴", level3: "1:1문의", level4: "개인(신용)정보 수집〮이용 및 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "abcu1901i_iframe01", depth: { level2: "전체메뉴", level3: "고객의 소리", level4: "개인(신용)정보 수집〮이용 및 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "abetc1759c_iframe01", depth: { level2: "전체메뉴", level3: "서비스 이용약관", level4: "전자금융거래 기본약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "abetc1759c_iframe02", depth: { level2: "전체메뉴", level3: "", level4: "NH올원뱅크 서비스 기본약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "abetc1759c_iframe03", depth: { level2: "전체메뉴", level3: "", level4: "개인(신용)정보 수집 이용 동의서(필수)", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "abetc1759c_iframe04", depth: { level2: "전체메뉴", level3: "", level4: "개인(신용)정보 제3자 제공 동의", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "abetc1759c_iframe05", depth: { level2: "전체메뉴", level3: "", level4: "NH올원뱅크 서비스 설명서", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "cs", pageID: "abetc1759c_iframe06", depth: { level2: "전체메뉴", level3: "", level4: "위치기반 서비스 기본약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "pay", pageID: "UI-PD-D11003", depth: { level2: "전체메뉴", level3: "", level4: "NH올원뱅크 해외결제 서비스 이용약관", level5: "", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: "해외결제 서비스 이용약관 동일 파일"},
        {path: "etc", pageID: "abcu1843r_iframe01", depth: { level2: "전체메뉴", level3: "올원뱅크소개", level4: "홈", level5: "올원뱅크 카톡으로 추천하기", level6: ""}, pageType: "", done: "", modify: "", status: "", note: ""},
        {path: "etc", pageID: "abcu1844r_iframe00", depth: { level2: "전체메뉴", level3: "", level4: "서비스소개", level5: "올원뱅크 영상", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        {path: "etc", pageID: "abcu1844r_iframe04", depth: { level2: "전체메뉴", level3: "", level4: "", level5: "올원뱅크 100%활용하기", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "etc", pageID: "abcu1844r_iframe03", depth: { level2: "전체메뉴", level3: "", level4: "올원뱅크 웹툰", level5: "웹툰", level6: ""}, pageType: "컨텐츠", done: "", modify: "", status: "", note: ""},
        

        // 큰글뱅킹
        {path: "big", pageID: "BB-00000000F02", depth: { level2: "큰글뱅킹", level3: "메인", level4: "", level5: "", level6: ""}, pageType: "배너", done: "", modify: "", status: "", note: ""},
        {path: "big", pageID: "BA-01020200F01-P", depth: { level2: "큰글뱅킹", level3: "전체메뉴", level4: "상담원문의", level5: "약관상세", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
        {path: "big", pageID: "BE-03010000F01-P", depth: { level2: "큰글뱅킹", level3: "전계좌조회", level4: "다른기관", level5: "어카운트인포 약관동의", level6: ""}, pageType: "약관", done: "", modify: "", status: "", note: ""},
    ]
}